### ISSUE TITLE
lega_codes.sqlite exceeding 3GB

### ISSUE THREAD

**Issue by KennethThompson** [parkerhancock/patent_client#146]
![image](https://github.com/parkerhancock/patent_client/assets/3701133/32d779a5-a6db-4cb0-afe3-690b4410f1bd)

Legal_codes.sqlite in EPO folder grows massively. Bug?  Maybe my version is too behind and you already addressed this

Thank you!

**Comment by parkerhancock** [comment]
Interesting. That's wierd. I'll need to look into it.

You will be happy to know that in v5, I've deferred updating the code database until you actually ask for a legal code the first time, so that should speed up loading the library, and eliminate the need for the db altogether if you don't need it!

**Comment by parkerhancock** [comment]
Found the issue! I wasn't dropping the table of old values when the codes were being deleted, so the code database was being polluted with excessive tags. Should be fixed in v5.0.2.

Thanks!
