### ISSUE TITLE
Async yields strangeness..

### ISSUE THREAD

**Issue by KennethThompson** [parkerhancock/patent_client#148]
Calling up PEDs queries seems to work great.  However, if I pass a returned 'app' object into processing routines, properties are not loaded and erroneous situations occur.

For example, if I query peds for any US application with assignments, I can't just check len(returnedapp.assignments) as it always returns zero.  However, if I assign returnedapp.assignments to a value and then do a for loop over the contents, e.g., for a in assign: print(a), then the async kicks in and the assignment elements get requested/made available.

Is this a known issue?  Thank you

**Comment by parkerhancock** [comment]
Fixed in v5! 

Now, if you want to use the pure synchronous interface, just import as normal directly from patent client, like this:

```python
from patent_client import USApplication

```

If you want the asynchronous interface, import from the new _async subpackage

```python
from patent_client._async import USApplication
```

And don't let the two mix! That was a hard lesson I had to learn, but I've learned it now!
