### ISSUE TITLE
make `patent_client` work behind a proxy

### ISSUE THREAD

**Issue by Mo-Gul** [parkerhancock/patent_client#72]
If I do e.g.

```python
from patent_client import Inpadoc
Inpadoc.objects.get("US2022323947A1")
```

when not sitting behind a proxy it works, but when I do sit behind a proxy I get

> ConnectionError: HTTPConnectionPool(host='ops.epo.org', port=80): Max retries exceeded with url: /3.2/rest-services/published-data/publication/docdb/US2022323947A1/biblio (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FB78C201F0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

Is there a simple way to make it work?

*(Excuse me if there is an "obvious" solution, but I am rather new to Python.)*

**Comment by parkerhancock** [comment]
This is not a common enough use case to support, but if you really want it to work, look at monkey-patching the Requests sessions to use proxies. All of the HTTP in patent_client is performed by the [Requests](https://requests.readthedocs.io/en/latest/) library. There are two customized `requests.Session` objects that support Patent Client:

- patent_client.session.session (an instance of patent_client.session.PatentClientSession)
- patent_client.epo.ops.session.session (an instance of patent_client.epo.ops.session.OpsSession)

Both inherit from `requests.Session`, and `requests_cache.Session`. I know that `requests.Session` [works with proxies](https://requests.readthedocs.io/en/latest/user/advanced/#proxies), so the trick would be modifying the session you're working with. Something like this:

```python
from patent_client.epo.ops.session import session

proxies = {
  'http': 'http://10.10.1.10:3128',
  'https': 'http://10.10.1.10:1080',
}

session.proxies.update(proxies)

```

Now because you've attached the proxies to the session that runs Inpadoc, it should just work. But again, that's my best effort at providing some guidance - I have no experience working with proxies.

**Comment by amotl** [comment]
Hi there,

we can confirm that using the environment variables `HTTP_PROXY`  and `HTTPS_PROXY` works. See https://github.com/panodata/grafana-client/issues/14.

With kind regards,
Andreas.

**Comment by Mo-Gul** [comment]
I can also confirm that the "Directly in your code" approach from [@parkerhancock's answer](https://github.com/parkerhancock/patent_client/issues/72#issuecomment-1290545181) works. Many thanks for the quick help!!
