### ISSUE TITLE
'cp949' codec can't decode

### ISSUE THREAD

**Issue by ioneme** [parkerhancock/patent_client#84]
hello.
I have contacted you. (An error occurred while using "patent_client" )

in jupyter
from patent_client import USApplication

~~
File c:\Python38\Lib\site-packages\patent_client\epo\ops\number_service\errors.py:36, in build_error_dir()
     34 error_text = (base_dir / "errors.txt").read_text()
     35 errors = [get_errors(err) for err in error_text.split("\n")]
---> 36 message_text = (base_dir / "messages.txt").read_text()
     37 messages = [get_messages(err) for err in message_text.split("\n")]
     38 error_objs = [NumberServiceError(**e) for e in errors + messages if e]

File c:\Python38\Lib\pathlib.py:1059, in Path.read_text(self, encoding, errors)
   1057 encoding = io.text_encoding(encoding)
   1058 with self.open(mode='r', encoding=encoding, errors=errors) as f:
-> 1059     return f.read()

**UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 102: illegal multibyte sequence**

Is this an easily solved problem?

**Comment by parkerhancock** [comment]
Yes, this is because your operating system locale is using cp949 (Windows in Korean) as its default encoding, rather than something that is ASCII compatible, like UTF-8 (unicode). Modern python assumes all computers everywhere use UTF-8, and it has a special UTF-8 Mode that can override the locale. It's a reasonable choice because Unicode includes characters from essentially all worldwide languages. Just set the `PYTHONUTF8` environment variable to 1 to override your locale and use Python's UTF-8 Mode.

See also:

- [Python UTF-8 Mode Documentation](https://docs.python.org/3/library/os.html#utf8-mode)
- [Python UTF-8 Environment Variable Documentation](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUTF8)

**Comment by ioneme** [comment]
I Really appreciate it.
