### ISSUE TITLE
TypeError: unsupported type for timedelta days component: str

### ISSUE THREAD

**Issue by ravitd10** [parkerhancock/patent_client#87]
Hi Parker, thanks for fixing the previous issue. However, I am now getting a TypeError when I try to run:

`app = USApplication.objects.get('15710770')`

Here's the error: 

`Traceback (most recent call last): File "C:\Users\ravit\PycharmProjects\patentApplication\simple_patent_app_retriever.py", line 1, in <module> from patent_client import USApplication File "C:\Users\ravit\AppData\Local\Programs\Python\Python39\lib\site-packages\patent_client\__init__.py", line 41, in <module> session = PatentClientSession() File "C:\Users\ravit\AppData\Local\Programs\Python\Python39\lib\site-packages\patent_client\session.py", line 15, in __init__ expire_after=datetime.timedelta(days=SETTINGS.CACHE.MAX_AGE), TypeError: unsupported type for timedelta days component: str`

I think the datetime.timedelta() function of the session.py module is expecting an integer for the days argument but it is being passed as a string.

**Comment by parkerhancock** [comment]
Fixed in v3.1.0!

**Comment by ravitd10** [comment]
It is working now. Thanks Parker. Let me know if you need any help with patent-client. 

I am a patent practitioner (agent) and code on the side :-)

**Comment by parkerhancock** [comment]
I am always in need of assistance with patent client! Right now, my biggest needs are to write docstrings in the USPTO Patent Public Search for the model attributes, and think about doing some model normalization (i.e. make sure the application number has the same attribute name across the various API's).

The easiest way to get started would be to fork the library, and then start putting in docstrings in [Patent Public Search](https://github.com/parkerhancock/patent_client/blob/e98ee30c480654e0b489d184c77284f505aca2d0/src/patent_client/uspto/public_search/model.py) that look like the ones in [Patent Examination Data](https://github.com/parkerhancock/patent_client/blob/e98ee30c480654e0b489d184c77284f505aca2d0/src/patent_client/uspto/peds/model.py).

Those annotations are super-useful in code editors, because you can type a model (like `USApplication`), and then type a . and get a list of all the attributes - with useful descriptions.

Let me know if that's of any interest to you. Thanks!
